### ISSUE TITLE
April (04)

### ISSUE THREAD

**Issue by UltiRequiem** [UltiRequiem/UltiRequiem#11]
# Tasks

- [ ] [Write a XO extension for coc.nvim](https://github.com/neoclide/coc.nvim/issues/3614)
- [ ] Make a file Explorer (Rust using [Diouxus](https://dioxuslabs.com) + [TailwindCSS](https://tailwindcss.com)]
- [ ] tailwind-run like [react-run](https://github.com/UltiRequiem/react-run) but on node.js
- [ ] Make a websockets server with Rust
- [ ] https://github.com/bxcodec/faker/issues/21
- [x] Web Framework
- [ ] `__dirname` and `__filename` for Browser, Node.js and Deno (The same package

![encanto-encanto-luisa](https://user-images.githubusercontent.com/71897736/156452982-e0c46106-e2c3-4816-aba1-fd24d8d2d8ae.gif))

**Comment by UltiRequiem** [comment]
Web Framework 👉🏽 https://kumeru.js.org/

**Comment by UltiRequiem** [comment]
AAAAAAAAAAAAAAAAAAAAAAA
